version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"

  # Maintain dependencies for Maven
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"

  # Maintain dependencies for Node.js (frontend)
  - package-ecosystem: "npm"
    directory: "/front-end"
    schedule:
      interval: "daily"
    target-branch: "main"

  # Maintain Docker base images
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
